// This file was automatically generated from own-error-types.md by Knit tool. Do not edit.
package arrow.core.examples.test

import kotlin.test.Test
import kotlinx.coroutines.test.runTest
import arrow.website.captureOutput
import kotlinx.knit.test.verifyOutputLines

class OwnErrorsTest {
  @Test fun ExampleOwnErrors01() = runTest {
    arrow.website.examples.exampleOwnErrors01.example()
  }

}
